### ISSUE TITLE
Licensing for BlizzMove

### ISSUE THREAD

**Issue by vallantv** [zanony/BlizzMove#11]
The curseforge site says this addon is All rights reserved. Would you consider doing something like MIT or the Unlicense?
https://unlicense.org/

**Comment by zanony** [comment]
Why? I would actually not want someone to just copy it and then monetise on it?

**Comment by vallantv** [comment]
What about something like GPL then? My point was if you weren't going to do a classic version i'd like to but with the current license on curseforge I'd need your permission.

**Comment by Numynum** [comment]
I'd suggest opening pull requests for classic support is a better and more logical way forward; since having multiple addons do the same thing on curseforge seems a bit silly to me
and you're correct, it's against the TOS to ask for payment in any way before handing over addon's source code
even giving perks to patreon supporters etc is tricky

**Comment by vallantv** [comment]
I agree. I've run into projects where the maintainers are afk so when a project has an all rights reserved license nothing can be done with the code. I think it's dumb that that is the default license type for a curseforge project.

**Comment by the-rebel-Mermaid** [comment]
Asking for money is agains the TOS of Blizzard but the Curseforge [reward system](https://authors.curseforge.com/knowledge-base/rewards/3448-how-to-join-and-redeem-rewards) ist not.

I am definitely ok with splitting the points with those that contribute a lot. 

If you post your user id here or message me in the discord I can also add you to the curse project after some meaningful contributions.

**Comment by vallantv** [comment]
Cool. Thanks for the update. Have you considered linking your github to creators.brave.com
