### ISSUE TITLE
Scrolling list of items/bosses in Adventure Guide does not work

### ISSUE THREAD

**Issue by zanony** [zanony/BlizzMove#14]
can't scroll list of items/bosses in Adventure Guide.

**Comment by zaCade** [comment]
You sure this still occurs when this code https://github.com/zanony/BlizzMove/blob/master/Handle.lua#L31 is there? Because for me that code fixed it.

**Comment by Numynum** [comment]
I personally didn't/don't have any issue with the Adventure Guide, so I'm not sure what's going wrong

**Comment by zaCade** [comment]
Ah the post reporting this issue was made before i fixed this. https://www.wowace.com/projects/blizzmove#c281
