### ISSUE TITLE
Moving the quest tracker causes glitches

### ISSUE THREAD

**Issue by zanony** [zanony/BlizzMove#15]
Moving the quest tracker was dibbled because it caused glitches.

![](https://i.imgur.com/FMQ4ocd.png)

**Comment by zaCade** [comment]
Any way on how i could replicate this bug? Because when i tested the moving of the quest trackers on my end, it all worked perfectly. Will test again today.

**Comment by Numynum** [comment]
@zaCade I think this is a glitchy interaction between the World Quest Tracker addon, and the questframe
personally I'd prefer being able to move the frame regardless, since blizzard sometimes puts it in silly positions when entering dungeons/raids
I might look into the reason for the glitchiness

**Comment by zaCade** [comment]
Well, it glitched once for me when the worldquest first got added when i logged in with just this addon active. But i cant seem to replicate that again. So its probably something wierd like that yeah,
just note, QuestWatchFrame is the classic version while ObjectiveTrackerFrame is for retail.

But if you do find something feel free to tag me, i'd be glad to help finding a solution to this.

**Comment by Numynum** [comment]
@zaCade WorldQuestTracker is doing some 'interesting' things, mostly to support the MoveAnything addon
I'm not sure of a fix yet, but the relevant code for WQT is in WorldQuestTracket_Tracker.lua:369

**Comment by Numynum** [comment]
@zaCade I figured the only generic, non-ugly fix seems to be to move the MoveAnything frames instead when they exist

**Comment by zaCade** [comment]
I saw, commented on it already. :D
